# Generated by Django 5.1.4 on 2025-01-05 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_field', models.CharField(max_length=100)),
                ('interest_domain', models.CharField(max_length=100)),
                ('programming_language', models.CharField(max_length=100)),
                ('frameworks', models.CharField(max_length=100)),
                ('cloud_and_database', models.CharField(max_length=100)),
                ('projects', models.TextField()),
                ('achievements_and_awards', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
