# Generated by Django 5.1.4 on 2025-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_system', '0002_alter_userprofiledata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledata',
            name='academic_year',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='userprofiledata',
            name='branch',
            field=models.CharField(null=True),
        ),
    ]
