# Generated by Django 5.1.4 on 2025-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_system', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='skills',
            field=models.TextField(),
        ),
    ]
